spring:
  mvc:
    static-path-pattern: /static/genetic_python/
  sql:
    init.mode: always
#  profiles:
#    include: oauth
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/areyoup?useSSL=false&serverTimezone=Asia/Seoul
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#        default_batch_fetch_size: 100
